[config]
reload_apps = false
scheme = "fruit_salad"
contrast = 0.0

[config.modes.dark]

[templates.niri]
input_path = "~/.config/matugen/templates/niri.kdl"
output_path = "~/.config/niri/colors.kdl"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

# Removed Zed (Handled by Pywal)
# Removed Kitty (Handled by Pywal)

[templates.vesktop]
input_path = "~/.config/matugen/templates/discord.css"
output_path = "~/.config/vesktop/themes/lis.theme.css"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"
